### ISSUE TITLE
Cart > Cart Item > Variants styles

### ISSUE THREAD

**Issue by khoipro** [codetot-web/ct-bones#534]
Khi 1 item có 2 variant trở lên, style hiện tại đang bị xô lệch khung.

**Comment by khoipro** [comment]
```css
.cart_item .product-name .variation p {
	margin: 0;
}
```

**Comment by khoipro** [comment]
```css
.shop_table.woocommerce-cart-form__contents .product-remove a {
  text-decoration: none;
}
```
